### PR TITLE
add uri connexion to mongodb

### PR DESCRIPTION
**Pull request by NicolasRisi**
# Problem
Could not connect to my mongo ATLAS server with error : ([Errno 8] nodename nor servname provided, or not known)
I can only connect with a URI like this one : mongodb+srv://<user>:<password>@xxx.yyy.gcp.mongodb.net/<db_auth>?retryWrites=true&w=majority

# Solution
config.json accept args host, user, password ....... or only the URI.
If URI is in config then required parameters are only Uri and database.
If not, then it's like before.

# QA steps
 - [ ] automated tests passing
 - [ ] manual QA steps passing (list below)

 
# Risks

# Rollback steps
 - Revert this branch

### CODE REVIEW

**Comment by Samira-El** [comment]
Hi,
Thanks for this PR, can you please elaborate a bit on your use case, why can you only use a url to create the connection?

**Comment by NicolasRisi** [comment]
Hi, It seems to be cause of the parameters in the URL : ?retryWrites=true&w=majority
If i don't pass those arguments, i can't connect on my Mongo Atlas cluster.

**Comment by Samira-El** [comment]
> Hi, It seems to be cause of the parameters in the URL : ?retryWrites=true&w=majority
> If i don't pass those arguments, i can't connect on my Mongo Atlas cluster.

Thanks for your reply.
I haven't dabbled in Atlas server before so I'm not sure what special connection params it requires, the tap was tested with standalone mongodb server v4.2.

So tap-mongodb only needs a user with read access, it doesn't make sense to me to have write params , i.e`?retryWrites=true&w=majority` in the connection. Have you tried creating a user with read access only?
Please find a guide here: https://transferwise.github.io/pipelinewise/connectors/taps/mongodb.html

**Comment by Samira-El** [comment]
Feature added by https://github.com/transferwise/pipelinewise-tap-mongodb/pull/37

**Pull request closed without merging**
